### ISSUE TITLE
Not fetching results properly from ls

### ISSUE THREAD

**Issue by wallace11** [tbodt/deoplete-tabnine#46]
Using `TabNine::sem` with `pyls`, suggestions from language server appear only after a couple of tries, as illustrated in the attached gif.

I even tried to force a higher timeout in `TabNine.toml`, which appears to have done nothing.
```
synchronous_triggers = ["."]
synchronous_timeout_ms = 1000
```

![output](https://user-images.githubusercontent.com/5497761/81758888-c43faa00-94cb-11ea-8b02-853f72b3e129.gif)

**Comment by Shougo** [comment]
This is not deoplete-tabnine's problem.
It is tabnine's problem.

You should ask it in tabnine side.
https://github.com/codota/TabNine/issues

**Comment by Shougo** [comment]
And it seems tabnine's semantic completion feature.
tabnine's semantic completion is option.
If the completion is slow like pyls, it will be skipped.

**Comment by Shougo** [comment]
Hm.  I have tested it and it works for me.
You need to wait the completion.

And please test the configuration.

```toml
[language.python]
command = "pyls"
install = [["pip", "install", "python-language-server"]]
synchronous_triggers = ["."]
synchronous_timeout_ms = 1000
```
